import { Poppins } from '@next/font/google';
import { Geist, Geist_Mono } from "next/font/google";
import { Kapakana } from '@next/font/google';
import "./globals.css";
import Script from 'next/script';
import { Toaster } from 'sonner';
import GlobalProvider from '@/components/application/GlobalProvider';
import ThemeProvider from '@/components/Application/Website/ThemeProvider'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap'
});

export const metadata = {
  title: "censored",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Script src="https://cdn.lordicon.com/lordicon.js"></Script>

      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange
        >

          <GlobalProvider>
            {children}
            <Toaster closeButton position="top-center" />
          </GlobalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
